### ISSUE TITLE
Helm chart instead of example manifests

### ISSUE THREAD

**Issue by jpruciak** [aleksasiriski/rffmpeg-worker#1]
Hello!
It would be veeery nice to have helm chart for this instead of plain manifests so things could be configurable without modifying it by hand!

**Comment by aleksasiriski** [comment]
> Hello!
> It would be veeery nice to have helm chart for this instead of plain manifests so things could be configurable without modifying it by hand!

I've been putting this off for some time now, I'll do it when I get a chance.
