### ISSUE TITLE
Add option to add ssh user to render group

### ISSUE THREAD

**Issue by helkaluin** [aleksasiriski/rffmpeg-worker#2]
Currently the SSH_USERS env var allows a pair of uid and gid, which in one of the common setups with Jellyfin and the whole *arr stack, would mean a Jelyfin uid, and a common gid shared among these media server applications. But doing so would mean that the jellyfin user within this Docker container can't access /dev/dri/render\*.

One work around is to specify the render group's gid as the gid in SSH_USERS, but that feels dirty since render is a system group, and could potentially screw up permissions when it writes. It'll be great if the user can specify a gid for the render group when running this container instead, and the entrepoint.sh would have one groupadd line to add that in-container user to that gid.

**Comment by aleksasiriski** [comment]
I'm a little busy these days, idk when I'll get around to maintaining rffmpeg-go and this repo. PRs are always welcome though
