### ISSUE TITLE
Can only connect once

### ISSUE THREAD

**Issue by btxlittle** [aleksasiriski/rffmpeg-worker#4]
This is my docker config
![image](https://github.com/aleksasiriski/rffmpeg-worker/assets/15058391/43ae9136-623f-4d7e-8e35-cdf34a51fe28)
When first start my jellyfin docker can connect to the worker docker, and trancscode is correct
When my jellyfin docker restart it can not connect, i have to restart my jellyfin docker and the worker docker

**Comment by aleksasiriski** [comment]
Sorry for the late response, have you managed to fix the issue?

**Comment by btxlittle** [comment]
> Sorry for the late response, have you managed to fix the issue?

No, I didn`t fix it. I think it may be the prolbem with the known_host issue. I haven`t try it . When i have spare time, i will try it
